joint_map:

    1: panda_joint_1
    2: panda_joint_2
    3: panda_joint_3
    4: panda_joint_4
    5: panda_joint_5
    6: panda_joint_6
    7: panda_joint_7
    8: panda_joint_8
    9: panda_joint_x
    10: panda_joint_y
    11: panda_joint_theta
   
